package dev.lukebemish.polymorphicsignatures.utilities;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/// Methods annotated with this are not considered public API in that they are not meant to be consumed directly except
/// through code generated by referencing public API that uses the method as a metafactory; the behavior of any use not
/// through a {@link dev.lukebemish.polymorphicsignatures.PolymorphicSignature} method call is undefined. However, they
/// are considered public binary API in the sense that their signature (and behavior for generated {@code INVOKEDYNAMIC}
/// through a polymorphic call) will be stable.
@Documented
@Retention(RetentionPolicy.CLASS)
@Target(ElementType.METHOD)
@interface ImplementationMetafactory {
}
